version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4200:4200"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # environment:
    #   - AIR_LIVE_RELOAD=1

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

